name: 'Build IBM ACE12'
description: 'Builds an IBM ACE12 project'
inputs:
  AppName:
    description: 'App Name'
    required: true
  ServiceName:
    description: 'Service Name'
    required: true
  INTEGRATIONAPI:
    description: 'Integration API'
    required: true
  INTEGRATIONACE:
    description: 'Integration ACE'
    required: true
runs:
  using: 'composite'
  steps:
    - run: java -cp /home/oem/Documentos/ACE/12.0-ACE-LINUXX64-12.0.7.0/ace-12.0.7.0/common/classes/IntegrationAPI.jar com.ibm.broker.config.appdev.FlowRendererBAR -w ${{ github.workspace }}/src -a ${{ inputs.AppName }}-${{ github.run_id }}.bar -k ${{ inputs.AppName }}
      shell: bash
    - run: /home/oem/Documentos/ACE/12.0-ACE-LINUXX64-12.0.7.0/ace-12.0.7.0/ace mqsiapplybaroverride -b ${{ inputs.AppName }}-${{ github.run_id }}.bar -p ${{ github.workspace }}/configuration/properties/${{ inputs.ServiceName }}_DEV.properties -r
      shell: bash
    - run: |
        mkdir -p ${{ github.workspace }}/initial-config/bars
        cp ${{ inputs.AppName }}-${{ github.run_id }}.bar ${{ github.workspace }}/initial-config/bars
      shell: bash
    - run: |
        mkdir -p ${{ github.workspace }}/initial-config/
        cp configuration/properties/*.properties ${{ github.workspace }}/initial-config/
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ inputs.ServiceName }}
        path: ${{ github.workspace }}/initial-config/
